"""Add name field to User model

Revision ID: 040ddfb4a42f
Revises: 57e110344e61
Create Date: 2025-05-25 23:05:04.743765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040ddfb4a42f'
down_revision = '57e110344e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
